### ISSUE TITLE
MiDaS Model Loader issue

### ISSUE THREAD

**Issue by picobyte** [Fannovel16/comfyui_controlnet_aux#108]
In a workflow with loading a Midas model for depth recognition I'm getting this error since my git update today:
```
Error occurred when executing MiDaS Model Loader:
attempted relative import beyond top-level package
```
with a trace that ends with
```

WAS Node Suite: Loading MiDaS Model from `ComfyUI/models/midas/checkpoints/dpt_large_384.pt`                                                 
Using cache found in ComfyUI/models/midas/intel-isl_MiDaS_master                                                                             
ERROR:root:!!! Exception during processing !!!                                                                                                                            
ERROR:root:Traceback (most recent call last):                                                                                                                             
  File "ComfyUI/execution.py", line 153, in recursive_execute                                                                                
    output_data, output_ui = get_output_data(obj, input_data_all)                                                                                                         
  File "ComfyUI/execution.py", line 83, in get_output_data                                                                                   
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)                                                                           
  File "ComfyUI/execution.py", line 76, in map_node_over_list                                                                                
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))                                                                                                   
  File "ComfyUI/custom_nodes/was-node-suite-comfyui/WAS_Node_Suite.py", line 8462, in load_midas_model                                       
    midas = torch.hub.load("intel-isl/MiDaS", midas_model, trust_repo=True)                                                                                               
  File "stable-diffusion-webui/venv310cu118/lib/python3.10/site-packages/torch/hub.py", line 558, in load                                    
    model = _load_local(repo_or_dir, model, *args, **kwargs)                                                                                                              
  File "stable-diffusion-webui/venv310cu118/lib/python3.10/site-packages/torch/hub.py", line 584, in _load_local                             
    hub_module = _import_module(MODULE_HUBCONF, hubconf_path)                                                                                                             
  File "stable-diffusion-webui/venv310cu118/lib/python3.10/site-packages/torch/hub.py", line 98, in _import_module                           
    spec.loader.exec_module(module)                                                                                                                                       
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module                                                                                                 
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed                                                                                            
  File "ComfyUI/models/midas/intel-isl_MiDaS_master/hubconf.py", line 5, in <module>                                                         
    from midas.dpt_depth import DPTDepthModel                                                                                                                             
  File "ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/midas/__init__.py", line 9, in <module>                               
    from ..util import HWC3, common_input_validate, resize_image_with_pad, annotator_ckpts_path, custom_hf_download                                                       
ImportError: attempted relative import beyond top-level package    
 File "ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/midas/__init__.py", line 9, in <module>                               
```

Edit2: ComfyUI and stable-diffusion-webui are in there but this is because the ComfyUI venv is a symlink to the table-diffusion-webui, which works just fine for me.

**Comment by picobyte** [comment]
part of the solution is
```
diff --git a/src/controlnet_aux/midas/__init__.py b/src/controlnet_aux/midas/__init__.py
index 31626af..0751624 100644
--- a/src/controlnet_aux/midas/__init__.py
+++ b/src/controlnet_aux/midas/__init__.py
@@ -6,9 +6,9 @@ import torch
 from einops import rearrange
 from PIL import Image
 
-from ..util import HWC3, common_input_validate, resize_image_with_pad, annotator_ckpts_path, custom_hf_download
-from .api import MiDaSInference
 
+from controlnet_aux.util import HWC3, common_input_validate, resize_image_with_pad, custom_hf_download, annotator_ckpts_path
+from controlnet_aux.midas.api import MiDaSInference
 
 class MidasDetector:
     def __init__(self, model):
diff --git a/src/controlnet_aux/midas/api.py b/src/controlnet_aux/midas/api.py
index 0cc8703..6d74750 100644
--- a/src/controlnet_aux/midas/api.py
+++ b/src/controlnet_aux/midas/api.py
@@ -10,7 +10,7 @@ from custom_midas_repo.midas.dpt_depth import DPTDepthModel
 from custom_midas_repo.midas.midas_net import MidasNet
 from custom_midas_repo.midas.midas_net_custom import MidasNet_small
 from custom_midas_repo.midas.transforms import Resize, NormalizeImage, PrepareForNet
-from ..util import annotator_ckpts_path
+from controlnet_aux.util import annotator_ckpts_path
 
 
 ISL_PATHS = {
```
but it is getting too late.

**Comment by Fannovel16** [comment]
@picobyte Your last issue is related to WAS, not this extension. Can you try `MiDaS - Depth Map`?

**Comment by Fannovel16** [comment]
Fixed in https://github.com/Fannovel16/comfyui_controlnet_aux/commit/8df8bed5ffa5e290d37bf05022017cda0e470615

**Comment by picobyte** [comment]
Yes I see, thanks for picking this up

**Comment by julien-blanchon** [comment]
This problem seems to still occurs even with the lastest version
